In [1]:
import sys
import os
sys.path.append(os.path.abspath(r"C:\Users\gabri\OneDrive\Desktop\Projects\Data Science\MoneyData"))
from api_func import *
import re
import pandas as pd

In [2]:
df =  get_finance_df()

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=69276656658-pvjsvjotq90maq7m0lj33arg13ij3e9d.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A65461%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspreadsheets.readonly&state=zubN9k9l2bOVUTQlhNtJAiCUko6Dcb&access_type=offline

In [3]:
df

,Data,Valor,Categoria,Descrição,Necessário,É parcelado,Parcela Atual,Numero de Parcelas,
0,01/07/2024,R$248.76,Carro,,Sim,Sim,2,3,
1,01/07/2024,R$465.40,Carro,,Sim,Sim,3,6,
2,01/07/2024,R$115.00,Saúde,,Sim,Sim,5,10,
3,01/07/2024,R$169.00,Outro,Anhembi,Sim,Não,,,
4,01/07/2024,R$300.00,Reino,Dizimo,Sim,Não,,,
...,...,...,...,...,...,...,...,...,...
330,01/12/2025,R$500.00,Reino,Dizimo,Sim,Não,,,
331,11/02/2025,R$55.00,Reino,O tempo não roubou a alegria,,,,,
332,04/02/2025,R$160.00,Outro,Taxa Google Play,,,,,
333,05/02/2025,"R$5,000.00",Entrada,Mesada,,,,,
334,22/02/2025,R$309.00,Gasolina,Posto Garcia,,,,,

In [8]:
df['Data'] = pd.to_datetime(df['Data'],format="%d/%m/%Y")
df['Ano'] = df['Data'].dt.year